package pluginsetting;

import org.openqa.selenium.chrome.ChromeDriver;
import java.util.List;
import java.util.concurrent.TimeUnit;
import org.openqa.selenium.interactions.Actions;
import java.lang.*;
import org.openqa.selenium.*;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.support.ui.Select;

public class Colorswatches {

  public static WebDriver driver;
	public void testColorswatches() throws Exception {
	   /* driver.findElement(By.xpath("//*[@id=\"menu-plugins\"]/a/div[3]")).click();
	    Thread.sleep(1000);
	    driver.findElement(By.xpath("//*[@id=\"the-list\"]/tr[9]/td[1]/div/span[1]/a")).click();
	 //   driver.findElement(By.xpath("(//a[contains(text(),'Settings')])[3]")).click();
	    driver.findElement(By.xpath("//div[@id='wpbody-content']/div[4]/div/form/div/div/div/table/tbody/tr/td[2]/label/span")).click();
	    driver.findElement(By.xpath("//div[@id='wpbody-content']/div[4]/div/form/div/div/div/table/tbody/tr/td[2]/label/span")).click();
	    Thread.sleep(2000);
	    driver.findElement(By.xpath("//div[@id='wpbody-content']/div[4]/div/form/div/div/div/table/tbody/tr[2]/td[2]/label/span")).click();
	    driver.findElement(By.xpath("//div[@id='wpbody-content']/div[4]/div/form/div/div/div/table/tbody/tr[2]/td[2]/label/span")).click();
	    Thread.sleep(2000);
	    driver.findElement(By.xpath("//div[@id='wpbody-content']/div[4]/div/form/div/div/div/table/tbody/tr[3]/td[2]/label/span")).click();
	    driver.findElement(By.xpath("//div[@id='wpbody-content']/div[4]/div/form/div/div/div/table/tbody/tr[3]/td[2]/label/span")).click();
	    Thread.sleep(2000);
	    driver.findElement(By.xpath("//div[@id='wpbody-content']/div[4]/div/form/div/div/div/table/tbody/tr[4]/td[2]/label/span")).click();
	    driver.findElement(By.xpath("//div[@id='wpbody-content']/div[4]/div/form/div/div/div/table/tbody/tr[4]/td[2]/label/span")).click();
	    Thread.sleep(2000);
	    driver.findElement(By.xpath("//div[@id='wpbody-content']/div[4]/div/form/div/div/div/table/tbody/tr[5]/td[2]/label/span")).click();
	    driver.findElement(By.xpath("//div[@id='wpbody-content']/div[4]/div/form/div/div/div/table/tbody/tr[5]/td[2]/label/span")).click();
	    Thread.sleep(2000);
	    driver.findElement(By.xpath("//div[@id='wpbody-content']/div[4]/div/form/div/div/div/table/tbody/tr[6]/td[2]/label/span")).click();
	    driver.findElement(By.xpath("//div[@id='wpbody-content']/div[4]/div/form/div/div/div/table/tbody/tr[6]/td[2]/label/span")).click();
	    Thread.sleep(2000);
	    new Select(driver.findElement(By.id("vas"))).selectByVisibleText("Tooltip");
	    driver.findElement(By.id("vas")).click();
	    Thread.sleep(2000);
	    new Select(driver.findElement(By.id("mwb_swatch_vm_atds2"))).selectByVisibleText("SQUARE");
	    driver.findElement(By.id("mwb_swatch_vm_atds2")).click();
	    new Select(driver.findElement(By.name("mwb_swatch_vm_atds1"))).selectByVisibleText("60px * 60px");
	    driver.findElement(By.name("mwb_swatch_vm_atds1")).click();
	    Thread.sleep(2000);
	    new Select(driver.findElement(By.name("mwb_swatch_vm_shop_size_attr"))).selectByVisibleText("35px * 35px");
	    driver.findElement(By.name("mwb_swatch_vm_shop_size_attr")).click();
	    driver.findElement(By.xpath("//div[@id='wpbody-content']/div[4]/div/form/div/div/div/table/tbody/tr[10]/td[2]")).click();
	    driver.findElement(By.xpath("//div[@id='wpbody-content']/div[4]/div/form/div/div/div/table/tbody/tr[11]/td")).click();
	    driver.findElement(By.name("save")).click();*/
	    Thread.sleep(2000);
	    driver.findElement(By.xpath("//li[@id='menu-posts-product']/a/div[3]")).click();
	    new Select(driver.findElement(By.id("dropdown_product_type"))).selectByVisibleText("Variable product");
	    driver.findElement(By.id("dropdown_product_type")).click();
	    Thread.sleep(2000);
	    System.out.println("product filtered succesfully");
	   
	    driver.findElement(By.id("post-query-submit")).click();
	    Thread.sleep(2000);
	    driver.findElement(By.linkText("T-shirt")).click();
	    Thread.sleep(1000);
		JavascriptExecutor jse = (JavascriptExecutor)driver;   
		jse.executeScript("window.scrollBy(0,500)", "");
	    driver.findElement(By.xpath("//div[@id='woocommerce-product-data']/div/div/ul/li[6]/a")).click();
	    Thread.sleep(2000);
	    System.out.println("succesfully 1");//*[@id="variable_product_options_inner"]/div[3]/div[1]/h3
	    driver.findElement(By.xpath("//*[@id=\"variable_product_options_inner\"]/div[3]/div[1]/h3")).click();
	    Thread.sleep(2000);
	    System.out.println("succesfully 1a");
	    driver.findElement(By.xpath("//div[@id='product_attributes']/div[2]/div/div/table/tbody/tr[2]/td/label")).click();
	    driver.findElement(By.xpath("//div[@id='product_attributes']/div[2]/div/div/table/tbody/tr[2]/td/label")).click();
	    driver.findElement(By.name("attribute_variation[0]")).click();
	    driver.findElement(By.name("attribute_variation[0]")).click();
	    Thread.sleep(1000);
	    System.out.println("succesfull2");
	    driver.findElement(By.xpath("//div[@id='product_attributes']/div[2]/div/div/table/tbody/tr/td[2]/button")).click();
	    driver.findElement(By.xpath("//div[@id='product_attributes']/div[3]")).click();
	    driver.findElement(By.xpath("(//button[@type='button'])[45]")).click();
	    Thread.sleep(1000);
	    System.out.println("succesfull3");
	   // driver.findElement(By.linkText("Variations")).click();
	  WebElement web=  driver.findElement(By.xpath("//*[@id=\"woocommerce-product-data\"]/div/div/ul/li[7]/a/span"));
	  Thread.sleep(2000);
	  Actions action = new Actions(driver);
	  action.moveToElement(web).click().perform();
	    System.out.println("succesfull4");
	    driver.findElement(By.xpath("//div[@id='variable_product_options_inner']/div[3]/div/h3")).click();
	    Thread.sleep(1000);
	    driver.findElement(By.xpath("//div[@id='variable_product_options_inner']/div[3]/div/h3")).click();
	    Thread.sleep(1000);
	    System.out.println("succesfull5");
	    driver.findElement(By.xpath("//div[@id='variable_product_options_inner']/div[3]/div[2]/h3")).click();
	    Thread.sleep(1000);
	    System.out.println("succesfull6");
	    driver.findElement(By.name("variable_manage_stock[1]")).click();
	    Thread.sleep(1000);
	    System.out.println("succesfull7");
	    driver.findElement(By.name("variable_manage_stock[1]")).click();
	    Thread.sleep(1000);
	    System.out.println("succesfull8");
	    driver.findElement(By.id("variable_regular_price_1")).click();
	    Thread.sleep(1000);
	    driver.findElement(By.id("variable_regular_price_1")).clear();
	    driver.findElement(By.id("variable_regular_price_1")).sendKeys("250");
	    driver.findElement(By.id("variable_stock1")).click();
	    driver.findElement(By.id("variable_stock1")).clear();
	    driver.findElement(By.id("variable_stock1")).sendKeys("52");
	    driver.findElement(By.id("variable_shipping_class[1]")).click();
	    driver.findElement(By.xpath("(//button[@type='button'])[46]")).click();
	    System.out.println("succesfull9");
	    JavascriptExecutor jsee = (JavascriptExecutor)driver;   
		jsee.executeScript("window.scrollBy(0,-600)", "");
		driver.findElement(By.className("swatches_options")).click();
	   // WebElement web1=  driver.findElement(By.xpath("//*div[@id='woocommerce-product-data']/div/div/ul/li[3]/a/span"));
	  //  WebElement web1=driver.findElement(By.className("swatches_options"));
	     System.out.println("succesfull10");
		  Thread.sleep(2000);
		 // Actions actions = new Actions(driver);
	//	  actions.moveToElement(web1).click().perform();
	  //  driver.findElement(By.xpath("//div[@id='woocommerce-product-data']/div/div/ul/li[3]/a/span")).click();
		 System.out.println("succesfull10a");
	    Thread.sleep(2000);
	   // driver.findElement(By.xpath("//div[@id='mwb_swatch-vm-accordion']/div/div/h4")).click();
	    System.out.println("succesfull11");
	    Thread.sleep(2000);
	    driver.findElement(By.name("mwb_swatch_vm_label_pa_color")).click();
	    Thread.sleep(2000);
	    driver.findElement(By.name("mwb_swatch_vm_label_pa_color")).clear();
	    driver.findElement(By.name("mwb_swatch_vm_label_pa_color")).sendKeys("Color");
	    Thread.sleep(2000);
	    new Select(driver.findElement(By.name("mwb_swatch_vm_dt_pa_color"))).selectByVisibleText("Image/Color");
	    driver.findElement(By.name("mwb_swatch_vm_dt_pa_color")).click();
	    Thread.sleep(2000);
	    new Select(driver.findElement(By.name("mwb_swatch_vm_ds_pa_color"))).selectByVisibleText("40px * 40px");
	    driver.findElement(By.name("mwb_swatch_vm_ds_pa_color")).click();
	    Thread.sleep(2000);
	    new Select(driver.findElement(By.name("mwb_swatch_vm_ds2_pa_color"))).selectByVisibleText("circle");
	    driver.findElement(By.name("mwb_swatch_vm_ds2_pa_color")).click();
	    driver.findElement(By.name("mwb_swatch_vm_dn_pa_color")).click();
	    driver.findElement(By.xpath("//div[@id='mwb_swatch-vm-accordion']/div/div[2]/div/div/div/h4")).click();
	    new Select(driver.findElement(By.name("mwb_swatch_vm_gat_black"))).selectByVisibleText("Yes");
	    driver.findElement(By.name("mwb_swatch_vm_gat_black")).click();
	    new Select(driver.findElement(By.name("mwb_swatch_vm_sdt_black"))).selectByVisibleText("Color");
	    driver.findElement(By.name("mwb_swatch_vm_sdt_black")).click();
	    driver.findElement(By.xpath("//div[@id='mwb_swatch-vm-accordion']/div/div[2]/div/div/div[2]/table/tbody/tr[4]/td[2]/div/button/span")).click();
	    driver.findElement(By.xpath("//div[@id='mwb_swatch-vm-accordion']/div/div[2]/div/div/div[2]/table/tbody/tr[4]/td[2]/div/div/div/div[2]/a")).click();
	    driver.findElement(By.xpath("//div[@id='mwb_swatch-vm-accordion']/div/div[2]/div/div/div[2]/table/tbody/tr[4]/td")).click();
	    driver.findElement(By.xpath("//div[@id='mwb_swatch-vm-accordion']/div/div[2]/div/div/div[3]/h4")).click();
	    new Select(driver.findElement(By.name("mwb_swatch_vm_gat_blue"))).selectByVisibleText("Yes");
	    driver.findElement(By.name("mwb_swatch_vm_gat_blue")).click();
	    new Select(driver.findElement(By.name("mwb_swatch_vm_sdt_blue"))).selectByVisibleText("Color");
	    driver.findElement(By.name("mwb_swatch_vm_sdt_blue")).click();
	    driver.findElement(By.xpath("//div[@id='mwb_swatch-vm-accordion']/div/div[2]/div/div/div[4]/table/tbody/tr[4]/td[2]/div/button/span")).click();
	    driver.findElement(By.xpath("//div[@id='mwb_swatch-vm-accordion']/div/div[2]/div/div/div[4]/table/tbody/tr[4]/td[2]/div/div/div/div[2]/a[7]")).click();
	    driver.findElement(By.xpath("//div[@id='mwb_swatch-vm-accordion']/div/div[2]/div/div/div[4]/table/tbody/tr[2]/td")).click();
	    driver.findElement(By.xpath("//div[@id='mwb_swatch-vm-accordion']/div/div[2]/div/div/div[5]/h4")).click();
	    new Select(driver.findElement(By.name("mwb_swatch_vm_gat_green"))).selectByVisibleText("Yes");
	    driver.findElement(By.name("mwb_swatch_vm_gat_green")).click();
	    driver.findElement(By.name("mwb_swatch_vm_sdt_green")).click();
	    driver.findElement(By.xpath("(//button[@type='button'])[52]")).click();
	    driver.findElement(By.xpath("//ul[@id='__attachments-view-39']/li[78]/div/div")).click();
	    driver.findElement(By.xpath("(//button[@type='button'])[277]")).click();
	    driver.findElement(By.xpath("//div[@id='mwb_swatch-vm-accordion']/div/div[2]/div/div/div[5]/h4")).click();
	    driver.findElement(By.id("publish")).click();
	    driver.findElement(By.linkText("Visit Store")).click();
	    driver.findElement(By.xpath("(//input[@name='show_variations'])[5]")).click();
	    driver.findElement(By.xpath("(//input[@id='attr_img_blue'])[3]")).click();
	    driver.findElement(By.xpath("(//input[@id='attr_img_black'])[4]")).click();
	    driver.findElement(By.xpath("//main[@id='main']/div[2]/ul/li[6]/a/img")).click();
	    driver.findElement(By.id("attr_img_green")).click();
	    driver.findElement(By.id("attr_img_blue")).click();
	    driver.findElement(By.id("attr_img_black")).click();
	    driver.findElement(By.xpath("(//button[@type='submit'])[2]")).click();
	    driver.findElement(By.xpath("(//a[contains(text(),'View cart')])[2]")).click();
	    driver.findElement(By.xpath("//ul[@id='shipping_method']/li[2]")).click();
	    driver.findElement(By.xpath("//ul[@id='shipping_method']/li[2]/label")).click();
	    driver.findElement(By.linkText("Proceed to checkout")).click();
	    driver.findElement(By.xpath("//div[@id='payment']/ul/li[3]/label")).click();
	    driver.findElement(By.id("place_order")).click();
	    driver.findElement(By.linkText("My account")).click();
	    driver.findElement(By.linkText("Orders")).click();
	    driver.findElement(By.linkText("View")).click();
	  }


	public static void main(String[] args) throws Exception {
		System.out.println("launching chrome browser");
		   System.setProperty("webdriver.chrome.driver","/home/cedcoss/Pictures/chromedriver");
		   driver = new ChromeDriver();
		   Colorswatches cs=new Colorswatches();
		   driver.navigate().to("https://localhost/shopping/wp-admin");
			Thread.sleep(2000);
		   driver.findElement(By.id("user_login")).clear();
			driver.findElement(By.id("user_login")).sendKeys("admin");
			driver.findElement(By.id("user_pass")).clear();
			driver.findElement(By.id("user_pass")).sendKeys("password");
			driver.findElement(By.id("rememberme")).click();
			driver.findElement(By.id("wp-submit")).submit();
			System.out.println("successfully logged in");
			   driver.manage().window().maximize();
		     Thread.sleep(3000);
		   cs.testColorswatches();

	}

}
